version: '2'

volumes:
  db_data: {}
services:
    web:
        build: ./
        ports:
            - "22122:8084"
        env_file:
            - ".env"
        depends_on:
            - db
    

    db:
        image: mariadb
        build: ./mysql
        environment:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: mysql
          MYSQL_USER: mysql
          MYSQL_PASSWORD: mysql
        volumes:
          - db_data:/var/lib/mysql/data